version: '3'

services:

  web:
    image: marvel/web
    build:
      context: ./frontend/marvel-comics
    ports:
      - 3000:3000
    volumes:
      - ./frontend/marvel-comics:/app
      - /app/node_modules
    depends_on:
      - gateway
    networks:
      - frontend

  gateway:
    image: marvel/gateway
    build:
      context: ./gateway
    ports:
      - 80:80
    depends_on:
      - characters
    volumes:
      - ./gateway:/etc/nginx/conf.d
    networks:
      - backend
      - frontend

  characters:
    image: marvel/characters
    restart: always
    build:
      context: ./services/characters
    volumes:
      - ./services/characters:/app
      - /app/node_modules
    ports:
      - 8000:8000
    depends_on:
      - rabbit
    networks:
      - backend

  powers:
    image: marvel/powers
    restart: always
    build:
      context: ./services/powers
    volumes:
      - ./services/powers:/app
      - /app/node_modules
    ports:
      - 8001:8001
    depends_on:
      - rabbit
    networks:
      - backend
    
  printer:
    image: marvel/printer
    restart: always
    build:
      context: ./services/printer
    volumes:
      - ./services/printer:/app
      - /app/node_modules
    ports:
      - 8002:8002
    depends_on:
      - rabbit
    networks:
      - backend
    
  rabbit:
    image: marvel/rabbit
    restart: always
    build:
      context: ./services/rabbit
    env_file:
      - ./services/rabbit/.env
    ports:
      - 15672:15672
      - 5672:5672
      - 25672:25672
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge